version: "3"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - "8888"
    ports:
      - "8888:8888"
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
    volumes:
      - ./:/code/
