FROM python:3.7-alpine

RUN apk update && \
    apk add --no-cache \
    icu-dev && \
    apk add python3 python3-dev build-base \
    gcc musl-dev linux-headers zlib zlib-dev \
    freetype freetype-dev libffi-dev pkgconfig

WORKDIR /code
COPY . /code/

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

#CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
